### PR TITLE
Redesign Update #1

### PR DESCRIPTION
**Pull request by aangel031**
I like the concept of your project so I decided to help by doing what I could. I did a redesign and changed the logic of your javascript by using jQuery, I also left the original code there just cause I didn't want to be rude lol.

### CODE REVIEW

**Comment by AlexHGaming** [comment]
Hey @aangel031, thanks for the PR!

I'm going to check this right now, see if it's better than my scruffy code, im too old for this lol

**Comment by AlexHGaming** [comment]
im too guillable for github rn, youve done a shit load man lmao

**Comment by aangel031** [comment]
There's more I would like to add if that's okay with you.

**Comment by AlexHGaming** [comment]
This seems okay for now, anything else that can massively help can be added.

Contributior role applied to the god thats better than me lol

**Comment by AlexHGaming** [comment]
I'll give you the right to make any edits now lol, thanks man it helps a lot.

**Pull request merged**
